# Size of the population
population_size: 2000
# Number of generations to evaluate
generation_limit: 5000
num_individuals_per_parents: 2
selection_ratio: 0.3
mutation_rate: 0.01
reinsertion_ratio: 0.5
